---
version: "3.2"

services:
  db:
    image: mariadb:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=password123456
    volumes:
      - /tmp/data_db:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - "node.hostname==worker1"
  web:
    hostname: web
    image: wordpress:latest
    depends_on: 
      - db
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password123456
    # volumes:
    #   - /tmp/plugins:/var/ww/htmlwp-content/plugins
    #   - /tmp/themes:/var/ww/htmlwp-content/themes
    #   - /tmp/uploads:/var/ww/htmlwp-content/uploads